/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.symposium.citytours.promociones.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Promocion service. Represents a row in the &quot;Citytours_Promocion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.symposium.citytours.promociones.model.impl.PromocionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.symposium.citytours.promociones.model.impl.PromocionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Promocion
 * @see com.liferay.symposium.citytours.promociones.model.impl.PromocionImpl
 * @see com.liferay.symposium.citytours.promociones.model.impl.PromocionModelImpl
 * @generated
 */
@ProviderType
public interface PromocionModel extends BaseModel<Promocion>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a promocion model instance should use the {@link Promocion} interface instead.
	 */

	/**
	 * Returns the primary key of this promocion.
	 *
	 * @return the primary key of this promocion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this promocion.
	 *
	 * @param primaryKey the primary key of this promocion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this promocion.
	 *
	 * @return the uuid of this promocion
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this promocion.
	 *
	 * @param uuid the uuid of this promocion
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the promocion ID of this promocion.
	 *
	 * @return the promocion ID of this promocion
	 */
	public long getPromocionId();

	/**
	 * Sets the promocion ID of this promocion.
	 *
	 * @param promocionId the promocion ID of this promocion
	 */
	public void setPromocionId(long promocionId);

	/**
	 * Returns the group ID of this promocion.
	 *
	 * @return the group ID of this promocion
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this promocion.
	 *
	 * @param groupId the group ID of this promocion
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this promocion.
	 *
	 * @return the company ID of this promocion
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this promocion.
	 *
	 * @param companyId the company ID of this promocion
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this promocion.
	 *
	 * @return the user ID of this promocion
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this promocion.
	 *
	 * @param userId the user ID of this promocion
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this promocion.
	 *
	 * @return the user uuid of this promocion
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this promocion.
	 *
	 * @param userUuid the user uuid of this promocion
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this promocion.
	 *
	 * @return the user name of this promocion
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this promocion.
	 *
	 * @param userName the user name of this promocion
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this promocion.
	 *
	 * @return the create date of this promocion
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this promocion.
	 *
	 * @param createDate the create date of this promocion
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this promocion.
	 *
	 * @return the modified date of this promocion
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this promocion.
	 *
	 * @param modifiedDate the modified date of this promocion
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the descripcion of this promocion.
	 *
	 * @return the descripcion of this promocion
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this promocion.
	 *
	 * @param descripcion the descripcion of this promocion
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the precio of this promocion.
	 *
	 * @return the precio of this promocion
	 */
	public double getPrecio();

	/**
	 * Sets the precio of this promocion.
	 *
	 * @param precio the precio of this promocion
	 */
	public void setPrecio(double precio);

	/**
	 * Returns the ciudad destino of this promocion.
	 *
	 * @return the ciudad destino of this promocion
	 */
	@AutoEscape
	public String getCiudadDestino();

	/**
	 * Sets the ciudad destino of this promocion.
	 *
	 * @param ciudadDestino the ciudad destino of this promocion
	 */
	public void setCiudadDestino(String ciudadDestino);

	/**
	 * Returns the nombre destinatario of this promocion.
	 *
	 * @return the nombre destinatario of this promocion
	 */
	@AutoEscape
	public String getNombreDestinatario();

	/**
	 * Sets the nombre destinatario of this promocion.
	 *
	 * @param nombreDestinatario the nombre destinatario of this promocion
	 */
	public void setNombreDestinatario(String nombreDestinatario);

	/**
	 * Returns the apellidos destinatario of this promocion.
	 *
	 * @return the apellidos destinatario of this promocion
	 */
	@AutoEscape
	public String getApellidosDestinatario();

	/**
	 * Sets the apellidos destinatario of this promocion.
	 *
	 * @param apellidosDestinatario the apellidos destinatario of this promocion
	 */
	public void setApellidosDestinatario(String apellidosDestinatario);

	/**
	 * Returns the nif destinatario of this promocion.
	 *
	 * @return the nif destinatario of this promocion
	 */
	@AutoEscape
	public String getNifDestinatario();

	/**
	 * Sets the nif destinatario of this promocion.
	 *
	 * @param nifDestinatario the nif destinatario of this promocion
	 */
	public void setNifDestinatario(String nifDestinatario);

	/**
	 * Returns the telefono destinatario of this promocion.
	 *
	 * @return the telefono destinatario of this promocion
	 */
	@AutoEscape
	public String getTelefonoDestinatario();

	/**
	 * Sets the telefono destinatario of this promocion.
	 *
	 * @param telefonoDestinatario the telefono destinatario of this promocion
	 */
	public void setTelefonoDestinatario(String telefonoDestinatario);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Promocion promocion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Promocion> toCacheModel();

	@Override
	public Promocion toEscapedModel();

	@Override
	public Promocion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}