/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.symposium.citytour.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Tipo service. Represents a row in the &quot;citytour_Tipo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.symposium.citytour.model.impl.TipoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.symposium.citytour.model.impl.TipoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Tipo
 * @see com.liferay.symposium.citytour.model.impl.TipoImpl
 * @see com.liferay.symposium.citytour.model.impl.TipoModelImpl
 * @generated
 */
@ProviderType
public interface TipoModel extends BaseModel<Tipo>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipo model instance should use the {@link Tipo} interface instead.
	 */

	/**
	 * Returns the primary key of this tipo.
	 *
	 * @return the primary key of this tipo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tipo.
	 *
	 * @param primaryKey the primary key of this tipo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this tipo.
	 *
	 * @return the uuid of this tipo
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this tipo.
	 *
	 * @param uuid the uuid of this tipo
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the tipo ID of this tipo.
	 *
	 * @return the tipo ID of this tipo
	 */
	public long getTipoId();

	/**
	 * Sets the tipo ID of this tipo.
	 *
	 * @param tipoId the tipo ID of this tipo
	 */
	public void setTipoId(long tipoId);

	/**
	 * Returns the group ID of this tipo.
	 *
	 * @return the group ID of this tipo
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tipo.
	 *
	 * @param groupId the group ID of this tipo
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tipo.
	 *
	 * @return the company ID of this tipo
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tipo.
	 *
	 * @param companyId the company ID of this tipo
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tipo.
	 *
	 * @return the user ID of this tipo
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tipo.
	 *
	 * @param userId the user ID of this tipo
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tipo.
	 *
	 * @return the user uuid of this tipo
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this tipo.
	 *
	 * @param userUuid the user uuid of this tipo
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tipo.
	 *
	 * @return the user name of this tipo
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tipo.
	 *
	 * @param userName the user name of this tipo
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tipo.
	 *
	 * @return the create date of this tipo
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tipo.
	 *
	 * @param createDate the create date of this tipo
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tipo.
	 *
	 * @return the modified date of this tipo
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tipo.
	 *
	 * @param modifiedDate the modified date of this tipo
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the label of this tipo.
	 *
	 * @return the label of this tipo
	 */
	@AutoEscape
	public String getLabel();

	/**
	 * Sets the label of this tipo.
	 *
	 * @param label the label of this tipo
	 */
	public void setLabel(String label);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Tipo tipo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Tipo> toCacheModel();

	@Override
	public Tipo toEscapedModel();

	@Override
	public Tipo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}