/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.symposium.citytour.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.liferay.symposium.citytour.model.Subtipo;
import com.liferay.symposium.citytour.model.SubtipoModel;
import com.liferay.symposium.citytour.model.SubtipoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Subtipo service. Represents a row in the &quot;citytour_Subtipo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SubtipoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubtipoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubtipoImpl
 * @see Subtipo
 * @see SubtipoModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class SubtipoModelImpl extends BaseModelImpl<Subtipo>
	implements SubtipoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subtipo model instance should use the {@link Subtipo} interface instead.
	 */
	public static final String TABLE_NAME = "citytour_Subtipo";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "subtipoId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "tipoId", Types.BIGINT },
			{ "label", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subtipoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("tipoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("label", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table citytour_Subtipo (uuid_ VARCHAR(75) null,subtipoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,tipoId LONG,label VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table citytour_Subtipo";
	public static final String ORDER_BY_JPQL = " ORDER BY subtipo.label ASC";
	public static final String ORDER_BY_SQL = " ORDER BY citytour_Subtipo.label ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(city.tour.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.symposium.citytour.model.Subtipo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(city.tour.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.symposium.citytour.model.Subtipo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(city.tour.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.symposium.citytour.model.Subtipo"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long LABEL_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Subtipo toModel(SubtipoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Subtipo model = new SubtipoImpl();

		model.setUuid(soapModel.getUuid());
		model.setSubtipoId(soapModel.getSubtipoId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTipoId(soapModel.getTipoId());
		model.setLabel(soapModel.getLabel());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Subtipo> toModels(SubtipoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Subtipo> models = new ArrayList<Subtipo>(soapModels.length);

		for (SubtipoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(city.tour.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.symposium.citytour.model.Subtipo"));

	public SubtipoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _subtipoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSubtipoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _subtipoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Subtipo.class;
	}

	@Override
	public String getModelClassName() {
		return Subtipo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("subtipoId", getSubtipoId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("tipoId", getTipoId());
		attributes.put("label", getLabel());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long subtipoId = (Long)attributes.get("subtipoId");

		if (subtipoId != null) {
			setSubtipoId(subtipoId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long tipoId = (Long)attributes.get("tipoId");

		if (tipoId != null) {
			setTipoId(tipoId);
		}

		String label = (String)attributes.get("label");

		if (label != null) {
			setLabel(label);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getSubtipoId() {
		return _subtipoId;
	}

	@Override
	public void setSubtipoId(long subtipoId) {
		_subtipoId = subtipoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getTipoId() {
		return _tipoId;
	}

	@Override
	public void setTipoId(long tipoId) {
		_tipoId = tipoId;
	}

	@JSON
	@Override
	public String getLabel() {
		if (_label == null) {
			return "";
		}
		else {
			return _label;
		}
	}

	@Override
	public void setLabel(String label) {
		_columnBitmask = -1L;

		if (_originalLabel == null) {
			_originalLabel = _label;
		}

		_label = label;
	}

	public String getOriginalLabel() {
		return GetterUtil.getString(_originalLabel);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Subtipo.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Subtipo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Subtipo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Subtipo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubtipoImpl subtipoImpl = new SubtipoImpl();

		subtipoImpl.setUuid(getUuid());
		subtipoImpl.setSubtipoId(getSubtipoId());
		subtipoImpl.setGroupId(getGroupId());
		subtipoImpl.setCompanyId(getCompanyId());
		subtipoImpl.setUserId(getUserId());
		subtipoImpl.setUserName(getUserName());
		subtipoImpl.setCreateDate(getCreateDate());
		subtipoImpl.setModifiedDate(getModifiedDate());
		subtipoImpl.setTipoId(getTipoId());
		subtipoImpl.setLabel(getLabel());

		subtipoImpl.resetOriginalValues();

		return subtipoImpl;
	}

	@Override
	public int compareTo(Subtipo subtipo) {
		int value = 0;

		value = getLabel().compareTo(subtipo.getLabel());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Subtipo)) {
			return false;
		}

		Subtipo subtipo = (Subtipo)obj;

		long primaryKey = subtipo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SubtipoModelImpl subtipoModelImpl = this;

		subtipoModelImpl._originalUuid = subtipoModelImpl._uuid;

		subtipoModelImpl._originalGroupId = subtipoModelImpl._groupId;

		subtipoModelImpl._setOriginalGroupId = false;

		subtipoModelImpl._originalCompanyId = subtipoModelImpl._companyId;

		subtipoModelImpl._setOriginalCompanyId = false;

		subtipoModelImpl._setModifiedDate = false;

		subtipoModelImpl._originalLabel = subtipoModelImpl._label;

		subtipoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Subtipo> toCacheModel() {
		SubtipoCacheModel subtipoCacheModel = new SubtipoCacheModel();

		subtipoCacheModel.uuid = getUuid();

		String uuid = subtipoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			subtipoCacheModel.uuid = null;
		}

		subtipoCacheModel.subtipoId = getSubtipoId();

		subtipoCacheModel.groupId = getGroupId();

		subtipoCacheModel.companyId = getCompanyId();

		subtipoCacheModel.userId = getUserId();

		subtipoCacheModel.userName = getUserName();

		String userName = subtipoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			subtipoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			subtipoCacheModel.createDate = createDate.getTime();
		}
		else {
			subtipoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			subtipoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			subtipoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		subtipoCacheModel.tipoId = getTipoId();

		subtipoCacheModel.label = getLabel();

		String label = subtipoCacheModel.label;

		if ((label != null) && (label.length() == 0)) {
			subtipoCacheModel.label = null;
		}

		return subtipoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", subtipoId=");
		sb.append(getSubtipoId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", tipoId=");
		sb.append(getTipoId());
		sb.append(", label=");
		sb.append(getLabel());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.symposium.citytour.model.Subtipo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subtipoId</column-name><column-value><![CDATA[");
		sb.append(getSubtipoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoId</column-name><column-value><![CDATA[");
		sb.append(getTipoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>label</column-name><column-value><![CDATA[");
		sb.append(getLabel());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Subtipo.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Subtipo.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _subtipoId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _tipoId;
	private String _label;
	private String _originalLabel;
	private long _columnBitmask;
	private Subtipo _escapedModel;
}