/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.symposium.citytours.promociones.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.petra.string.StringBundler;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.liferay.symposium.citytours.promociones.model.Promocion;
import com.liferay.symposium.citytours.promociones.model.PromocionModel;
import com.liferay.symposium.citytours.promociones.model.PromocionSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Promocion service. Represents a row in the &quot;Citytours_Promocion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link PromocionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PromocionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PromocionImpl
 * @see Promocion
 * @see PromocionModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class PromocionModelImpl extends BaseModelImpl<Promocion>
	implements PromocionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a promocion model instance should use the {@link Promocion} interface instead.
	 */
	public static final String TABLE_NAME = "Citytours_Promocion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "promocionId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "descripcion", Types.VARCHAR },
			{ "precio", Types.DOUBLE },
			{ "ciudadDestino", Types.VARCHAR },
			{ "nombreDestinatario", Types.VARCHAR },
			{ "apellidosDestinatario", Types.VARCHAR },
			{ "nifDestinatario", Types.VARCHAR },
			{ "telefonoDestinatario", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("promocionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("descripcion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("precio", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("ciudadDestino", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nombreDestinatario", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("apellidosDestinatario", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nifDestinatario", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("telefonoDestinatario", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table Citytours_Promocion (uuid_ VARCHAR(75) null,promocionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,descripcion VARCHAR(75) null,precio DOUBLE,ciudadDestino VARCHAR(75) null,nombreDestinatario VARCHAR(75) null,apellidosDestinatario VARCHAR(75) null,nifDestinatario VARCHAR(75) null,telefonoDestinatario VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Citytours_Promocion";
	public static final String ORDER_BY_JPQL = " ORDER BY promocion.descripcion ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Citytours_Promocion.descripcion ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.symposium.citytours.promociones.citytours.promociones.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.symposium.citytours.promociones.model.Promocion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.symposium.citytours.promociones.citytours.promociones.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.symposium.citytours.promociones.model.Promocion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.symposium.citytours.promociones.citytours.promociones.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.symposium.citytours.promociones.model.Promocion"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long DESCRIPCION_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long PROMOCIONID_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Promocion toModel(PromocionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Promocion model = new PromocionImpl();

		model.setUuid(soapModel.getUuid());
		model.setPromocionId(soapModel.getPromocionId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDescripcion(soapModel.getDescripcion());
		model.setPrecio(soapModel.getPrecio());
		model.setCiudadDestino(soapModel.getCiudadDestino());
		model.setNombreDestinatario(soapModel.getNombreDestinatario());
		model.setApellidosDestinatario(soapModel.getApellidosDestinatario());
		model.setNifDestinatario(soapModel.getNifDestinatario());
		model.setTelefonoDestinatario(soapModel.getTelefonoDestinatario());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Promocion> toModels(PromocionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Promocion> models = new ArrayList<Promocion>(soapModels.length);

		for (PromocionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.symposium.citytours.promociones.citytours.promociones.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.symposium.citytours.promociones.model.Promocion"));

	public PromocionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _promocionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPromocionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _promocionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Promocion.class;
	}

	@Override
	public String getModelClassName() {
		return Promocion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("promocionId", getPromocionId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("descripcion", getDescripcion());
		attributes.put("precio", getPrecio());
		attributes.put("ciudadDestino", getCiudadDestino());
		attributes.put("nombreDestinatario", getNombreDestinatario());
		attributes.put("apellidosDestinatario", getApellidosDestinatario());
		attributes.put("nifDestinatario", getNifDestinatario());
		attributes.put("telefonoDestinatario", getTelefonoDestinatario());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long promocionId = (Long)attributes.get("promocionId");

		if (promocionId != null) {
			setPromocionId(promocionId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String descripcion = (String)attributes.get("descripcion");

		if (descripcion != null) {
			setDescripcion(descripcion);
		}

		Double precio = (Double)attributes.get("precio");

		if (precio != null) {
			setPrecio(precio);
		}

		String ciudadDestino = (String)attributes.get("ciudadDestino");

		if (ciudadDestino != null) {
			setCiudadDestino(ciudadDestino);
		}

		String nombreDestinatario = (String)attributes.get("nombreDestinatario");

		if (nombreDestinatario != null) {
			setNombreDestinatario(nombreDestinatario);
		}

		String apellidosDestinatario = (String)attributes.get(
				"apellidosDestinatario");

		if (apellidosDestinatario != null) {
			setApellidosDestinatario(apellidosDestinatario);
		}

		String nifDestinatario = (String)attributes.get("nifDestinatario");

		if (nifDestinatario != null) {
			setNifDestinatario(nifDestinatario);
		}

		String telefonoDestinatario = (String)attributes.get(
				"telefonoDestinatario");

		if (telefonoDestinatario != null) {
			setTelefonoDestinatario(telefonoDestinatario);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPromocionId() {
		return _promocionId;
	}

	@Override
	public void setPromocionId(long promocionId) {
		_columnBitmask |= PROMOCIONID_COLUMN_BITMASK;

		if (!_setOriginalPromocionId) {
			_setOriginalPromocionId = true;

			_originalPromocionId = _promocionId;
		}

		_promocionId = promocionId;
	}

	public long getOriginalPromocionId() {
		return _originalPromocionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDescripcion() {
		if (_descripcion == null) {
			return "";
		}
		else {
			return _descripcion;
		}
	}

	@Override
	public void setDescripcion(String descripcion) {
		_columnBitmask = -1L;

		if (_originalDescripcion == null) {
			_originalDescripcion = _descripcion;
		}

		_descripcion = descripcion;
	}

	public String getOriginalDescripcion() {
		return GetterUtil.getString(_originalDescripcion);
	}

	@JSON
	@Override
	public double getPrecio() {
		return _precio;
	}

	@Override
	public void setPrecio(double precio) {
		_precio = precio;
	}

	@JSON
	@Override
	public String getCiudadDestino() {
		if (_ciudadDestino == null) {
			return "";
		}
		else {
			return _ciudadDestino;
		}
	}

	@Override
	public void setCiudadDestino(String ciudadDestino) {
		_ciudadDestino = ciudadDestino;
	}

	@JSON
	@Override
	public String getNombreDestinatario() {
		if (_nombreDestinatario == null) {
			return "";
		}
		else {
			return _nombreDestinatario;
		}
	}

	@Override
	public void setNombreDestinatario(String nombreDestinatario) {
		_nombreDestinatario = nombreDestinatario;
	}

	@JSON
	@Override
	public String getApellidosDestinatario() {
		if (_apellidosDestinatario == null) {
			return "";
		}
		else {
			return _apellidosDestinatario;
		}
	}

	@Override
	public void setApellidosDestinatario(String apellidosDestinatario) {
		_apellidosDestinatario = apellidosDestinatario;
	}

	@JSON
	@Override
	public String getNifDestinatario() {
		if (_nifDestinatario == null) {
			return "";
		}
		else {
			return _nifDestinatario;
		}
	}

	@Override
	public void setNifDestinatario(String nifDestinatario) {
		_nifDestinatario = nifDestinatario;
	}

	@JSON
	@Override
	public String getTelefonoDestinatario() {
		if (_telefonoDestinatario == null) {
			return "";
		}
		else {
			return _telefonoDestinatario;
		}
	}

	@Override
	public void setTelefonoDestinatario(String telefonoDestinatario) {
		_telefonoDestinatario = telefonoDestinatario;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Promocion.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Promocion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Promocion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Promocion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PromocionImpl promocionImpl = new PromocionImpl();

		promocionImpl.setUuid(getUuid());
		promocionImpl.setPromocionId(getPromocionId());
		promocionImpl.setGroupId(getGroupId());
		promocionImpl.setCompanyId(getCompanyId());
		promocionImpl.setUserId(getUserId());
		promocionImpl.setUserName(getUserName());
		promocionImpl.setCreateDate(getCreateDate());
		promocionImpl.setModifiedDate(getModifiedDate());
		promocionImpl.setDescripcion(getDescripcion());
		promocionImpl.setPrecio(getPrecio());
		promocionImpl.setCiudadDestino(getCiudadDestino());
		promocionImpl.setNombreDestinatario(getNombreDestinatario());
		promocionImpl.setApellidosDestinatario(getApellidosDestinatario());
		promocionImpl.setNifDestinatario(getNifDestinatario());
		promocionImpl.setTelefonoDestinatario(getTelefonoDestinatario());

		promocionImpl.resetOriginalValues();

		return promocionImpl;
	}

	@Override
	public int compareTo(Promocion promocion) {
		int value = 0;

		value = getDescripcion().compareTo(promocion.getDescripcion());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Promocion)) {
			return false;
		}

		Promocion promocion = (Promocion)obj;

		long primaryKey = promocion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		PromocionModelImpl promocionModelImpl = this;

		promocionModelImpl._originalUuid = promocionModelImpl._uuid;

		promocionModelImpl._originalPromocionId = promocionModelImpl._promocionId;

		promocionModelImpl._setOriginalPromocionId = false;

		promocionModelImpl._originalGroupId = promocionModelImpl._groupId;

		promocionModelImpl._setOriginalGroupId = false;

		promocionModelImpl._originalCompanyId = promocionModelImpl._companyId;

		promocionModelImpl._setOriginalCompanyId = false;

		promocionModelImpl._setModifiedDate = false;

		promocionModelImpl._originalDescripcion = promocionModelImpl._descripcion;

		promocionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Promocion> toCacheModel() {
		PromocionCacheModel promocionCacheModel = new PromocionCacheModel();

		promocionCacheModel.uuid = getUuid();

		String uuid = promocionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			promocionCacheModel.uuid = null;
		}

		promocionCacheModel.promocionId = getPromocionId();

		promocionCacheModel.groupId = getGroupId();

		promocionCacheModel.companyId = getCompanyId();

		promocionCacheModel.userId = getUserId();

		promocionCacheModel.userName = getUserName();

		String userName = promocionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			promocionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			promocionCacheModel.createDate = createDate.getTime();
		}
		else {
			promocionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			promocionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			promocionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		promocionCacheModel.descripcion = getDescripcion();

		String descripcion = promocionCacheModel.descripcion;

		if ((descripcion != null) && (descripcion.length() == 0)) {
			promocionCacheModel.descripcion = null;
		}

		promocionCacheModel.precio = getPrecio();

		promocionCacheModel.ciudadDestino = getCiudadDestino();

		String ciudadDestino = promocionCacheModel.ciudadDestino;

		if ((ciudadDestino != null) && (ciudadDestino.length() == 0)) {
			promocionCacheModel.ciudadDestino = null;
		}

		promocionCacheModel.nombreDestinatario = getNombreDestinatario();

		String nombreDestinatario = promocionCacheModel.nombreDestinatario;

		if ((nombreDestinatario != null) && (nombreDestinatario.length() == 0)) {
			promocionCacheModel.nombreDestinatario = null;
		}

		promocionCacheModel.apellidosDestinatario = getApellidosDestinatario();

		String apellidosDestinatario = promocionCacheModel.apellidosDestinatario;

		if ((apellidosDestinatario != null) &&
				(apellidosDestinatario.length() == 0)) {
			promocionCacheModel.apellidosDestinatario = null;
		}

		promocionCacheModel.nifDestinatario = getNifDestinatario();

		String nifDestinatario = promocionCacheModel.nifDestinatario;

		if ((nifDestinatario != null) && (nifDestinatario.length() == 0)) {
			promocionCacheModel.nifDestinatario = null;
		}

		promocionCacheModel.telefonoDestinatario = getTelefonoDestinatario();

		String telefonoDestinatario = promocionCacheModel.telefonoDestinatario;

		if ((telefonoDestinatario != null) &&
				(telefonoDestinatario.length() == 0)) {
			promocionCacheModel.telefonoDestinatario = null;
		}

		return promocionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", promocionId=");
		sb.append(getPromocionId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", descripcion=");
		sb.append(getDescripcion());
		sb.append(", precio=");
		sb.append(getPrecio());
		sb.append(", ciudadDestino=");
		sb.append(getCiudadDestino());
		sb.append(", nombreDestinatario=");
		sb.append(getNombreDestinatario());
		sb.append(", apellidosDestinatario=");
		sb.append(getApellidosDestinatario());
		sb.append(", nifDestinatario=");
		sb.append(getNifDestinatario());
		sb.append(", telefonoDestinatario=");
		sb.append(getTelefonoDestinatario());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.liferay.symposium.citytours.promociones.model.Promocion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>promocionId</column-name><column-value><![CDATA[");
		sb.append(getPromocionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descripcion</column-name><column-value><![CDATA[");
		sb.append(getDescripcion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>precio</column-name><column-value><![CDATA[");
		sb.append(getPrecio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ciudadDestino</column-name><column-value><![CDATA[");
		sb.append(getCiudadDestino());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombreDestinatario</column-name><column-value><![CDATA[");
		sb.append(getNombreDestinatario());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>apellidosDestinatario</column-name><column-value><![CDATA[");
		sb.append(getApellidosDestinatario());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nifDestinatario</column-name><column-value><![CDATA[");
		sb.append(getNifDestinatario());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefonoDestinatario</column-name><column-value><![CDATA[");
		sb.append(getTelefonoDestinatario());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Promocion.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Promocion.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _promocionId;
	private long _originalPromocionId;
	private boolean _setOriginalPromocionId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _descripcion;
	private String _originalDescripcion;
	private double _precio;
	private String _ciudadDestino;
	private String _nombreDestinatario;
	private String _apellidosDestinatario;
	private String _nifDestinatario;
	private String _telefonoDestinatario;
	private long _columnBitmask;
	private Promocion _escapedModel;
}