/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.symposium.citytour.uad.uad.anonymizer;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;

import com.liferay.symposium.citytour.uad.uad.constants.CitytourUADConstants;
import com.liferay.symposium.citytours.promotions.model.Promotion;
import com.liferay.symposium.citytours.promotions.service.PromotionLocalService;

import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the promotion UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link PromotionUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BasePromotionUADAnonymizer
	extends DynamicQueryUADAnonymizer<Promotion> {
	@Override
	public void autoAnonymize(Promotion promotion, long userId,
		User anonymousUser) throws PortalException {
		if (promotion.getUserId() == userId) {
			promotion.setUserId(anonymousUser.getUserId());
			promotion.setUserName(anonymousUser.getFullName());
		}

		promotionLocalService.updatePromotion(promotion);
	}

	@Override
	public void delete(Promotion promotion) throws PortalException {
		promotionLocalService.deletePromotion(promotion);
	}

	@Override
	public Class<Promotion> getTypeClass() {
		return Promotion.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return promotionLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return CitytourUADConstants.USER_ID_FIELD_NAMES_PROMOTION;
	}

	@Reference
	protected PromotionLocalService promotionLocalService;
}